# Generated by Django 6.1.1 on 2026-09-06 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OKRGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('quarter', models.CharField(default='Q3-2026', max_length=20)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Sin Iniciar'), ('IN_PROGRESS', 'En Progreso'), ('COMPLETED', 'Completado'), ('AT_RISK', 'En Riesgo')], default='IN_PROGRESS', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='okrs', to='authentication.department')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='okrs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KeyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('target_value', models.FloatField(default=100.0)),
                ('current_value', models.FloatField(default=0.0)),
                ('unit', models.CharField(default='%', max_length=30)),
                ('weight', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('okr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_results', to='okrs.okrgoal')),
            ],
        ),
    ]
